modified

diff --git a/helm/ecommerce-go-service/Makefile b/helm/ecommerce-go-service/Makefile
--- a/helm/ecommerce-go-service/Makefile
+++ b/helm/ecommerce-go-service/Makefile
@@ -10,7 +10,7 @@ HOSTS_FILE     := /etc/hosts
 TEMPLATE_FILE  := $(CHART_PATH)rendered.yaml
 
 .PHONY: all
-all: update deploy
+all: update deploy add-hosts
 
 .PHONY: deploy
 deploy:
@@ -36,3 +36,25 @@ render:
 	helm template $(APP_NAME) $(CHART_PATH) \
 		-n $(NAMESPACE) \
 		-f $(VALUES_FILE) > $(TEMPLATE_FILE)
+
+.PHONY: add-hosts
+add-hosts:
+	@echo "⏳ Rendering Helm templates to $(TEMPLATE_FILE)..."
+	@helm template $(APP_NAME) $(CHART_PATH) -f $(VALUES_FILE) > $(TEMPLATE_FILE)
+
+	@echo "🔍 Found Ingress hosts:"
+	@grep -E '[ -]+host:' $(TEMPLATE_FILE) \
+	| sed -E 's/.*host:[[:space:]]*"?([^"]+)"?/\1/' \
+	| grep -v '^#' | grep -v '^$$' \
+	| sort -u \
+	| tee /tmp/_hosts_to_add.txt
+
+	@echo "🛠️  Adding DNS names to /etc/hosts if missing..."
+	@cat /tmp/_hosts_to_add.txt | while read host; do \
+		if ! grep -q "$$host" $(HOSTS_FILE); then \
+			echo "$(HOST_IP) $$host" | sudo tee -a $(HOSTS_FILE) > /dev/null; \
+			echo "✅ Added: $$host"; \
+		else \
+			echo "🔁 Already exists: $$host"; \
+		fi; \
+	done
